### ISSUE TITLE
As a developer, I want aggregated javadocs

### ISSUE THREAD

**Issue by epag** [NOAA-OWP/wres#102]
---

Author Name: **James** (James)
Original Redmine Issue: 111532, https://vlab.noaa.gov/redmine/issues/111532
Original Date: 2023-01-12
Original Assignee: James

---

Given a build of WRES that requires aggregated javadocs
When the build executes
Then there should be a working build option to generate aggregated javadocs

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2023-01-12T15:01:42Z

---

Originally broken in #63732. Suggestion in #62732-80, which is now possible, since we use gradle 7.6, although I am not super optimistic.

**Comment by epag** [comment]
---

Original Redmine Comment
Author Name: **James** (James)
Original Date: 2023-01-12T16:02:36Z

---

Same issue as the other plugins, not surprising, this is not a plugin-specific issue.

Have more important things to do and this could be a tricky one to fix. There are several reports online, but nothing obvious that is confirmed as working.

```
> Task :aggregateJavadoc
<SNIP>\wres\wres-messages\src\main\java\module-info.java:1: error: too
 many module declarations found
module wres.messages
^
<SNIP>\wres\wres-worker\src\module-info.java:1: error: too many module
 declarations found
module wres.worker
^
error: the unnamed module reads package io.netty.handler.ssl.ocsp from both io.netty.hand
ler.ssl.ocsp and io.netty.handler
error: the unnamed module reads package io.netty.handler.codec.xml from both io.netty.cod
ec.xml and io.netty.codec
.
.
.
.

```
